/**********************************/
/* Table Name: PILL */
/**********************************/
DROP TABLE PILL;

CREATE TABLE PILL(
PILL_NO NUMBER(10) PRIMARY KEY,
DNO NUMBER(10) NOT NULL,
EFFICACY_NO NUMBER(10) NOT NULL,
SIDE NUMBER(10) NOT NULL,
PILL_NAME VARCHAR(30),
FOREIGN KEY(DNO) REFERENCES DISEASE(DNO),
FOREIGN KEY(EFFICACY_NO) REFERENCES EFFICACY(EFFICACY_NO),
FOREIGN KEY(SIDE) REFERENCES SIDE(SIDE)
);