/**********************************/
/* Table Name: MANAGER */
/**********************************/
DROP TABLE MANAGER;

CREATE TABLE   MENAGER(
MANAGER_NO number(10) PRIMARY KEY,
MANAGER_ID VARCHAR2(30) NOT NULL,
MANAGER_PASSWD VARCHAR2(60) NOT NULL,
MANAGER_NAME VARCHAR2(30) NOT NULL,
MANAGER_DATE DATE NOT NULL
);