/**********************************/
/* Table Name: MANAGER */
/**********************************/
DROP TABLE MANAGER;

commit;

CREATE TABLE   MANAGER(
MANAGER_NO number(10) NOT NULL,
MANAGER_ID VARCHAR2(30) NOT NULL,
MANAGER_PASSWD VARCHAR2(60) NOT NULL,
MANAGER_NAME VARCHAR2(30) NOT NULL,
MANAGER_DATE DATE NOT NULL,
PRIMARY KEY (manager_no)
);

COMMENT ON TABLE MANAGER is '관리자';
COMMENT ON COLUMN MANAGER.MANAGER_NO is '관리자 번호';
COMMENT ON COLUMN MANAGER.MANAGER_ID is '아이디';
COMMENT ON COLUMN MANAGER.MANAGER_PASSWD is '비밀번호';
COMMENT ON COLUMN MANAGER.MANAGER_NAME is '성명';
COMMENT ON COLUMN MANAGER.MANAGER_DATE is '가입일';

commit;